// GENERATED FILE - DO NOT EDIT. Regenerate with the app `generateWidgetThemeResources` task.
package com.a3.yearlyprogess.feature.widgets.domain.model

import androidx.annotation.StyleRes
import com.a3.yearlyprogess.R

enum class WidgetTheme(
    @param:StyleRes val themeRes: Int,
    val displayName: String,
    val seedArgb: Int
) {
    DEFAULT(R.style.WidgetTheme_Default, "Default", 0xFF276688L.toInt()),
    GREEN(R.style.WidgetTheme_Green, "Green", 0xFF3C6A1FL.toInt()),
    OCEAN(R.style.WidgetTheme_Ocean, "Ocean Blue", 0xFF0284C7L.toInt()),
    SUNSET(R.style.WidgetTheme_Sunset, "Sunset Orange", 0xFFEA580CL.toInt()),
    PURPLE(R.style.WidgetTheme_Purple, "Purple Dream", 0xFF9333EAL.toInt()),
    ROSE(R.style.WidgetTheme_Rose, "Rose Pink", 0xFFE11D48L.toInt()),
    MINT(R.style.WidgetTheme_Mint, "Mint Fresh", 0xFF059669L.toInt()),
    CORAL(R.style.WidgetTheme_Coral, "Coral", 0xFFF43F5EL.toInt()),
    SKY(R.style.WidgetTheme_Sky, "Sky Blue", 0xFF0284C7L.toInt()),
    FOREST(R.style.WidgetTheme_Forest, "Forest Green", 0xFF15803DL.toInt()),
    AMBER(R.style.WidgetTheme_Amber, "Amber Glow", 0xFFD97706L.toInt()),
    TEAL(R.style.WidgetTheme_Teal, "Teal Wave", 0xFF0D9488L.toInt()),
    LAVENDER(R.style.WidgetTheme_Lavender, "Lavender", 0xFF7C3AEDL.toInt()),
    CRIMSON(R.style.WidgetTheme_Crimson, "Crimson", 0xFFE11D48L.toInt()),
    INDIGO(R.style.WidgetTheme_Indigo, "Indigo Night", 0xFF4F46E5L.toInt()),
    PEACH(R.style.WidgetTheme_Peach, "Peach", 0xFFEA580CL.toInt()),
    CYAN(R.style.WidgetTheme_Cyan, "Cyan Electric", 0xFF0891B2L.toInt()),
    MAGENTA(R.style.WidgetTheme_Magenta, "Magenta", 0xFFC026D3L.toInt()),
    LIME(R.style.WidgetTheme_Lime, "Lime", 0xFF65A30DL.toInt()),
    RUBY(R.style.WidgetTheme_Ruby, "Ruby Red", 0xFFDC2626L.toInt()),
    SLATE(R.style.WidgetTheme_Slate, "Slate Gray", 0xFF475569L.toInt()),
    EMERALD(R.style.WidgetTheme_Emerald, "Emerald", 0xFF059669L.toInt()),
    FUCHSIA(R.style.WidgetTheme_Fuchsia, "Fuchsia", 0xFFC026D3L.toInt()),
    YELLOW(R.style.WidgetTheme_Yellow, "Yellow Sunshine", 0xFFCA8A04L.toInt()),
    VIOLET(R.style.WidgetTheme_Violet, "Violet", 0xFF7C3AEDL.toInt()),
    STEEL(R.style.WidgetTheme_Steel, "Steel Blue", 0xFF1D4ED8L.toInt()),
    BRONZE(R.style.WidgetTheme_Bronze, "Bronze", 0xFFC2782EL.toInt()),
    AQUA(R.style.WidgetTheme_Aqua, "Aqua", 0xFF0D9488L.toInt()),
    CHERRY(R.style.WidgetTheme_Cherry, "Cherry Blossom", 0xFFDB2777L.toInt()),
    NAVY(R.style.WidgetTheme_Navy, "Navy", 0xFF1E40AFL.toInt()),
    SAGE(R.style.WidgetTheme_Sage, "Sage Green", 0xFF16A34AL.toInt()),
    BURGUNDY(R.style.WidgetTheme_Burgundy, "Burgundy", 0xFFBE123CL.toInt()),
    CHARCOAL(R.style.WidgetTheme_Charcoal, "Charcoal", 0xFF4B5563L.toInt()),
    TURQUOISE(R.style.WidgetTheme_Turquoise, "Turquoise", 0xFF0F766EL.toInt()),
    MAUVE(R.style.WidgetTheme_Mauve, "Mauve", 0xFF7C3AEDL.toInt()),
    GOLD(R.style.WidgetTheme_Gold, "Gold", 0xFFD97706L.toInt()),
    SEAFOAM(R.style.WidgetTheme_Seafoam, "Seafoam", 0xFF059669L.toInt()),
    RASPBERRY(R.style.WidgetTheme_Raspberry, "Raspberry", 0xFFBE185DL.toInt()),
    MIDNIGHT(R.style.WidgetTheme_Midnight, "Midnight", 0xFF4338CAL.toInt()),
    OLIVE(R.style.WidgetTheme_Olive, "Olive", 0xFF4D7C0FL.toInt()),
    SALMON(R.style.WidgetTheme_Salmon, "Salmon", 0xFFDC2626L.toInt()),
    PERIWINKLE(R.style.WidgetTheme_Periwinkle, "Periwinkle", 0xFF6366F1L.toInt()),
    AUTUMN(R.style.WidgetTheme_Autumn, "Autumn", 0xFFC2410CL.toInt()),
    GRAPHITE(R.style.WidgetTheme_Graphite, "Graphite", 0xFF525252L.toInt()),
    SPRING(R.style.WidgetTheme_Spring, "Spring", 0xFF16A34AL.toInt()),
    BLUSH(R.style.WidgetTheme_Blush, "Blush", 0xFFE11D48L.toInt()),
    COBALT(R.style.WidgetTheme_Cobalt, "Cobalt", 0xFF1E40AFL.toInt()),
    PISTACHIO(R.style.WidgetTheme_Pistachio, "Pistachio", 0xFF4D7C0FL.toInt()),
    MOCHA(R.style.WidgetTheme_Mocha, "Mocha", 0xFF92643AL.toInt()),
    LILAC(R.style.WidgetTheme_Lilac, "Lilac", 0xFF7C3AEDL.toInt()),
    TANGERINE(R.style.WidgetTheme_Tangerine, "Tangerine", 0xFFC2410CL.toInt()),
    ARCTIC(R.style.WidgetTheme_Arctic, "Arctic", 0xFF0284C7L.toInt()),
    PLUM(R.style.WidgetTheme_Plum, "Plum", 0xFF7E22CEL.toInt()),
    HONEYDEW(R.style.WidgetTheme_Honeydew, "Honeydew", 0xFF16A34AL.toInt()),
    DYNAMIC(R.style.WidgetTheme_Dynamic, "Dynamic Colors", 0)
}
