package com.a3.yearlyprogess.feature.widgets.domain.model

import androidx.annotation.StyleRes
import com.a3.yearlyprogess.R

enum class WidgetTheme(
    @param:StyleRes val themeRes: Int,
    val displayName: String
) {
    DEFAULT(R.style.WidgetTheme_Default, "Default"),
    GREEN(R.style.WidgetTheme_Green, "Green"),
    OCEAN(R.style.WidgetTheme_Ocean, "Ocean Blue"),
    SUNSET(R.style.WidgetTheme_Sunset, "Sunset Orange"),
    PURPLE(R.style.WidgetTheme_Purple, "Purple Dream"),
    ROSE(R.style.WidgetTheme_Rose, "Rose Pink"),
    MINT(R.style.WidgetTheme_Mint, "Mint Fresh"),
    CORAL(R.style.WidgetTheme_Coral, "Coral"),
    SKY(R.style.WidgetTheme_Sky, "Sky Blue"),
    FOREST(R.style.WidgetTheme_Forest, "Forest Green"),
    AMBER(R.style.WidgetTheme_Amber, "Amber Glow"),
    TEAL(R.style.WidgetTheme_Teal, "Teal Wave"),
    LAVENDER(R.style.WidgetTheme_Lavender, "Lavender"),
    CRIMSON(R.style.WidgetTheme_Crimson, "Crimson"),
    INDIGO(R.style.WidgetTheme_Indigo, "Indigo Night"),
    PEACH(R.style.WidgetTheme_Peach, "Peach"),
    CYAN(R.style.WidgetTheme_Cyan, "Cyan Electric"),
    MAGENTA(R.style.WidgetTheme_Magenta, "Magenta"),
    LIME(R.style.WidgetTheme_Lime, "Lime"),
    RUBY(R.style.WidgetTheme_Ruby, "Ruby Red"),
    SLATE(R.style.WidgetTheme_Slate, "Slate Gray"),
    EMERALD(R.style.WidgetTheme_Emerald, "Emerald"),
    FUCHSIA(R.style.WidgetTheme_Fuchsia, "Fuchsia"),
    YELLOW(R.style.WidgetTheme_Yellow, "Yellow Sunshine"),
    VIOLET(R.style.WidgetTheme_Violet, "Violet"),
    STEEL(R.style.WidgetTheme_Steel, "Steel Blue"),
    BRONZE(R.style.WidgetTheme_Bronze, "Bronze"),
    AQUA(R.style.WidgetTheme_Aqua, "Aqua"),
    CHERRY(R.style.WidgetTheme_Cherry, "Cherry Blossom"),
    NAVY(R.style.WidgetTheme_Navy, "Navy"),
    SAGE(R.style.WidgetTheme_Sage, "Sage Green"),
    BURGUNDY(R.style.WidgetTheme_Burgundy, "Burgundy"),
    CHARCOAL(R.style.WidgetTheme_Charcoal, "Charcoal"),
    TURQUOISE(R.style.WidgetTheme_Turquoise, "Turquoise"),
    MAUVE(R.style.WidgetTheme_Mauve, "Mauve"),
    GOLD(R.style.WidgetTheme_Gold, "Gold"),
    SEAFOAM(R.style.WidgetTheme_Seafoam, "Seafoam"),
    RASPBERRY(R.style.WidgetTheme_Raspberry, "Raspberry"),
    MIDNIGHT(R.style.WidgetTheme_Midnight, "Midnight"),
    OLIVE(R.style.WidgetTheme_Olive, "Olive"),
    SALMON(R.style.WidgetTheme_Salmon, "Salmon"),
    PERIWINKLE(R.style.WidgetTheme_Periwinkle, "Periwinkle"),
    AUTUMN(R.style.WidgetTheme_Autumn, "Autumn"),
    GRAPHITE(R.style.WidgetTheme_Graphite, "Graphite"),
    SPRING(R.style.WidgetTheme_Spring, "Spring"),
    BLUSH(R.style.WidgetTheme_Blush, "Blush"),
    COBALT(R.style.WidgetTheme_Cobalt, "Cobalt"),
    PISTACHIO(R.style.WidgetTheme_Pistachio, "Pistachio"),
    MOCHA(R.style.WidgetTheme_Mocha, "Mocha"),
    LILAC(R.style.WidgetTheme_Lilac, "Lilac"),
    TANGERINE(R.style.WidgetTheme_Tangerine, "Tangerine"),
    ARCTIC(R.style.WidgetTheme_Arctic, "Arctic"),
    PLUM(R.style.WidgetTheme_Plum, "Plum"),
    HONEYDEW(R.style.WidgetTheme_Honeydew, "Honeydew"),
    DYNAMIC(R.style.WidgetTheme_Dynamic, "Dynamic Colors")
}