name: Build Release App Bundle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Decode keys
        id: decode_keys
        uses: timheuer/base64-to-file@v1.1
        with:
            fileName: 'api_keys.xml'
            encodedString: ${{ secrets.API_KEYS }}
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install tree
        run: sudo apt install tree
      - name: List all dir
        run: tree /home/runner/work/
      - name: Move file api_keys
        run: sudo mv /home/runner/work/_temp/api_keys.xml /home/runner/work/yearly_progress/yearly_progress/app/src/main/res/values/
      - name: List all dir
        run: tree /home/runner/work/