name: App Bundle Experimental

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Decode keys
        id: decode_keys
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'api_keys.xml'
          encodedString: ${{ secrets.API_KEYS }}

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Make folder keystore
        run: mkdir -p /home/runner/work/yearly-progress/yearly-progress/app/keystore/

      - name: Move file keystore.jks
        run: mv /home/runner/work/_temp/keystore.jks /home/runner/work/yearly-progress/yearly-progress/app/keystore/

      - name: Move file api_keys
        run: mv /home/runner/work/_temp/api_keys.xml /home/runner/work/yearly-progress/yearly-progress/app/src/main/res/values/

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build AAB
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Build APK
        run: ./gradlew app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload AAB and APKs
        uses: actions/upload-artifact@v3
        with:
          name: Bundles and APKs
          path: app/build/outputs/
